"""Tabelas Pacientes, Profissionais e Consultas criadas.

Revision ID: 0d3d129a3f23
Revises: 
Create Date: 2026-02-06 23:43:13.162712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d3d129a3f23'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data_nascimento', sa.Integer(), nullable=False),
    sa.Column('genero', sa.Enum('MASCULINO', 'FEMININO', 'OUTRO', 'NAO_INFOMRAR', name='genero_enum'), nullable=False),
    sa.Column('telefone', sa.Integer(), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('profissionais',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('nascimento', sa.Integer(), nullable=False),
    sa.Column('genero', sa.Enum('MASCULINO', 'FEMININO', 'OUTRO', 'NAO_INFOMRAR', name='genero_enum'), nullable=False),
    sa.Column('crm', sa.String(length=15), nullable=False),
    sa.Column('especialidade', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultas',
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('profissional_id', sa.UUID(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('AGENDADA', 'CONFIRMADA', 'CANCELADA', 'CONCLUIDA', 'FALTOU', name='status_enum'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultas_paciente_id'), 'consultas', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_consultas_profissional_id'), 'consultas', ['profissional_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultas_profissional_id'), table_name='consultas')
    op.drop_index(op.f('ix_consultas_paciente_id'), table_name='consultas')
    op.drop_table('consultas')
    op.drop_table('profissionais')
    op.drop_table('pacientes')
    # ### end Alembic commands ###
