"""Adicionado cpf na tabela de Pacientes.

Revision ID: 34cb028d8da6
Revises: 0d3d129a3f23
Create Date: 2026-02-07 15:41:57.739213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34cb028d8da6'
down_revision: Union[str, Sequence[str], None] = '0d3d129a3f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('cpf', sa.String(length=11), nullable=False))
    op.create_index(op.f('ix_pacientes_cpf'), 'pacientes', ['cpf'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profissionais', 'especialidade',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_pacientes_cpf'), table_name='pacientes')
    op.alter_column('pacientes', 'endereco',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('pacientes', 'telefone',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('pacientes', 'cpf')
    # ### end Alembic commands ###
